services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    env_file: .env
    depends_on: [db]
    ports:
      - "5050:80"

  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on: [db]
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  dbdata:
